### ISSUE TITLE
React 19, NextJS15 Error 

### ISSUE THREAD

**Issue by meabed** [samhirtarif/react-audio-recorder#136]
Hi There,

During build with nextjs 15 and react 19 - you get an error 

```
unhandledRejection TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
    at fr (node_modules/react-audio-voice-recorder/dist/react-audio-voice-recorder.es.js:18:176)
    at <unknown> (node_modules/react-audio-voice-recorder/dist/react-audio-voice-recorder.es.js:628:54) {
  type: 'TypeError'
}
```

**Comment by 0x0pharaoh** [comment]
hi @meabed is there any temporary solution for this issue ?

**Comment by meabed** [comment]
No - I just copied the component locally.

**Comment by 0x0pharaoh** [comment]
Can you please help me out how do you have implemented ? this issue actually came from [here](https://github.com/samhirtarif/react-audio-visualize) [#33](https://github.com/samhirtarif/react-audio-visualize/issues/33)
